### ISSUE TITLE
Xamarin Forms compiling Issues in Visual Studio 2019 - Xamarin Forms iOS

### ISSUE THREAD

**Issue by pasha-o** [JimmyPun610/BarcodeScanner.XF#60] opened 2021-04-23 03:43 UTC
Following your instructions to include the NuGet, if you use the visual studio for windows. it doesn't build for the iOS project, however, it compiles through the visual studio for mac.

Microsoft Visual Studio Enterprise 2019 Version 16.9.4
VisualStudio.Mac 1.0
Xamarin 16.9.000.273 (d16-9@1bba9e0)
Xamarin.Android SDK 11.2.2.1 (d16-9/877f572)
Xamarin.iOS and Xamarin.Mac SDK 14.14.2.5 (3836759d4)

Error
'/Users/sensio/Library/Caches/Xamarin/mtbs/builds/dre.iOS/0c29abbdfbe8303ee579ef50f6080ef7b8a6c1ad5e75432d99b6a024ccea7e7e/bin/iPhone/Debug/device-builds/iphone12.8-14.4.2/dre.iOS.exe' dre.iOS C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets 425

**Comment by JimmyPun610** [comment] 2021-04-23 06:45
Hi @pasha-o 

Thank you for the report. It looks there are some problems on building the app in Visual Studio for Windows recently. Unfortunately I do not have a Windows to figure the cause out.
My suggestion is updating all related software including
1. Visual Studio for Windows
2. Visual Studio for Mac
3. MacOS and XCode

After that, try to do below:
1. Disable Hot-Restart for iOS in Visual Studio for Windows
2. Clean the solution and rebuild it
3. Set the iOS project linker behavior to no link (link with SDK should be work also)
4. Set the architecture to ARM64

Could you send me build output?
I think this issue should be fixed by Microsoft.

**Comment by pasha-o** [comment] 2021-04-23 22:58
sure I will do the check and update you here, however, this issue might be related to the libraries themselves.

**Comment by JimmyPun610** [comment] 2021-04-26 10:36
> sure I will do the check and update you here, however, this issue might be related to the libraries themselves.

That could be true, but the core part of the library does not update for a while and I used to build it with Windows without any issue.

**Closed** 2021-05-05 00:23 UTC
Labels: help wanted
